//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightChelCompanyProject.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FreightChelCompanyEntities : DbContext
    {
        public FreightChelCompanyEntities()
            : base("name=FreightChelCompanyEntities")
        {
        }

        private static FreightChelCompanyEntities Context;
        public static FreightChelCompanyEntities GetContext()
        {
            if (Context == null)
                Context = new FreightChelCompanyEntities();
            return Context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PickupPoints> PickupPoints { get; set; }
        public virtual DbSet<ProdsInRequests> ProdsInRequests { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
