//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightChelCompanyProject.AppData
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Orders
    {
        public int Id { get; set; }
        public int NumWorker { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Status { get; set; }
        public int ArchStatus { get; set; }
        public string CheckReport
        {
            get
            {
                var report = FreightChelCompanyEntities.GetContext().Reports.Where(p => p.Id == Id).ToList();
                if (report.Count() > 0)
                {
                    return "Оформлен";
                }
                else
                {
                    return "Отсутствует";
                }
            }
            set
            {
                CheckReport = value;
            }
        }
        public virtual Requests Requests { get; set; }
        public virtual Workers Workers { get; set; }
        public virtual Reports Reports { get; set; }
    }
}
