//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreightChelCompanyProject.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoints
    {
        public int Id { get; set; }
        public string Address { get; set; }
    }
}
